# This set is fed in as arguments to a derivation which
# generates a config file.
{
  name = "pab_dev_env";

  # Database generated by plutus-pab migrate
  db-file = "/tmp/pab-core.db";

  # Ports
  webserver-port       = "9080";
  walletserver-port    = "9081";
  nodeserver-port      = "9082";
  chain-index-port     = "9083";
  signing-process-port = "9084";
  metadata-server-port = "9085";

  # I think this is the number of wallets to set up
  wallet = "1";

}
